onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/clk
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/srst
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/instr_name
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/instr
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/zero
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/jump
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/branch
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/result_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/mem_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/alu_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/imm_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/reg_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/pc_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/alu_control
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/read_data
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/write_data
add wave -noupdate -radix unsigned /tb_risc_core/i_top_riscv_single_cycle/ALUresult
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/pc
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/instr
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/zero
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/jump
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/branch
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/result_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/mem_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/alu_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/imm_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/reg_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/pc_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/alu_control
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/op_code
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/funct3
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/funct7
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_controller/alu_op
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/clk
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/srst
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/branch
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/result_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/mem_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/alu_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/imm_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/reg_w
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/pc_src
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/alu_control
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/instr
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/read_data
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/write_data
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/ALUresult
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/pc
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/zero
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/pc_next
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/Addr
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/imm
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/imm_ext
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/scrA
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/scrB
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/A1
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/A2
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/A3
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/WE3
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/RD1
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/RD2
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/a
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/b
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/alu_cntrl
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/pc_target
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/pc_plus4
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/f_mux_out
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/WD3
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/negative
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/carry
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_datapath/over_flow
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_instr_mem/Addr
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_instr_mem/RD
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/clk
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/srst
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/WE
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/A
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/WD
add wave -noupdate /tb_risc_core/i_top_riscv_single_cycle/i_data_memory/RD
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {61 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {157 ps}
